package com.example.workoutanalyzer.ui.theme

import androidx.compose.ui.graphics.Color

val PrimaryLight = Color(0xFF00668A)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFC4E7FF)
val OnPrimaryContainerLight = Color(0xFF001F2C)
val SecondaryLight = Color(0xFF4D616C)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFD0E6F3)
val OnSecondaryContainerLight = Color(0xFF091E28)
val TertiaryLight = Color(0xFF5E5A7D)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFE4DFFF)
val OnTertiaryContainerLight = Color(0xFF1B1836)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFF6FAFE)
val OnBackgroundLight = Color(0xFF181C1F)
val SurfaceLight = Color(0xFFF6FAFE)
val OnSurfaceLight = Color(0xFF181C1F)
val SurfaceVariantLight = Color(0xFFDCE4E9)
val OnSurfaceVariantLight = Color(0xFF40484C)
val OutlineLight = Color(0xFF70787D)

val PrimaryDark = Color(0xFF75D1FF)
val OnPrimaryDark = Color(0xFF00354A)
val PrimaryContainerDark = Color(0xFF004D69)
val OnPrimaryContainerDark = Color(0xFFC4E7FF)
val SecondaryDark = Color(0xFFB4CAD6)
val OnSecondaryDark = Color(0xFF1F333D)
val SecondaryContainerDark = Color(0xFF364954)
val OnSecondaryContainerDark = Color(0xFFD0E6F3)
val TertiaryDark = Color(0xFFC7C2EA)
val OnTertiaryDark = Color(0xFF2F2D4C)
val TertiaryContainerDark = Color(0xFF464464)
val OnTertiaryContainerDark = Color(0xFFE4DFFF)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF101416)
val OnBackgroundDark = Color(0xFFE0E3E6)
val SurfaceDark = Color(0xFF101416)
val OnSurfaceDark = Color(0xFFE0E3E6)
val SurfaceVariantDark = Color(0xFF40484C)
val OnSurfaceVariantDark = Color(0xFFC0C8CD)
val OutlineDark = Color(0xFF8A9297)
